from __future__ import annotations

from pathlib import Path

from bobr.core.change import ChangeStatus
from bobr.core.change_storage import (
    get_existing_artifacts,
    list_changes,
    parse_tasks,
)
from bobr.core.repo import BobrPaths


def generate_context(paths: BobrPaths, task_id: str | None = None) -> str:
    """Generate agent context markdown from project state.

    Collects: project info, requirements summaries, specs, active changes,
    backlog status, and conventions.

    If task_id is given, includes only relevant context for that task.
    """
    sections: list[str] = []

    sections.append(_header(paths))
    sections.append(_requirements_section(paths))
    sections.append(_specs_section(paths))
    sections.append(_active_changes_section(paths))
    sections.append(_backlog_section(paths, task_id))
    sections.append(_conventions_section(paths))

    return "\n\n".join(s for s in sections if s)


def _header(paths: BobrPaths) -> str:
    config = paths.bobr / "config.yaml"
    project_name = paths.root.name
    lines = [
        f"# {project_name} — Agent Context",
        "",
        f"> Auto-generated by `bobr context generate`. Do not edit manually.",
        f"> Project root: {paths.root}",
    ]
    return "\n".join(lines)


def _requirements_section(paths: BobrPaths) -> str:
    req_dir = paths.bobr / "requirements"
    if not req_dir.exists():
        return ""

    lines = ["## Requirements", ""]
    files = sorted(req_dir.glob("*.md"))
    if not files:
        return ""

    for f in files:
        text = f.read_text()
        # Extract first heading or first non-empty line as summary
        summary = _first_heading(text) or f.stem
        # Include first ~20 lines as overview
        preview = _truncate(text, max_lines=30)
        lines.append(f"### {summary}")
        lines.append("")
        lines.append(preview)
        lines.append("")

    return "\n".join(lines)


def _specs_section(paths: BobrPaths) -> str:
    specs_dir = paths.bobr / "specs"
    if not specs_dir.exists():
        return ""

    spec_dirs = sorted(
        d for d in specs_dir.iterdir()
        if d.is_dir() and d.name != "changes"
    )
    if not spec_dirs:
        return ""

    lines = ["## Specifications", ""]
    for d in spec_dirs:
        spec_file = d / "spec.md"
        if not spec_file.exists():
            continue
        text = spec_file.read_text()
        heading = _first_heading(text) or d.name
        lines.append(f"### {heading}")
        lines.append("")
        lines.append(_truncate(text, max_lines=40))
        lines.append("")

    return "\n".join(lines)


def _active_changes_section(paths: BobrPaths) -> str:
    changes = list_changes(paths.bobr)
    if not changes:
        return ""

    lines = ["## Active Changes", ""]
    for c in changes:
        cpath = paths.changes / c.name
        arts = get_existing_artifacts(cpath)
        tasks = parse_tasks(cpath)
        tasks_str = f"{tasks['done']}/{tasks['total']}" if tasks["total"] > 0 else "no tasks"

        lines.append(f"- **{c.title}** (`{c.name}`) — status: {c.status.value}, "
                      f"artifacts: {', '.join(arts)}, tasks: {tasks_str}")
        if c.promotes:
            lines.append(f"  - Promotes: {c.promotes}")

    lines.append("")
    return "\n".join(lines)


def _backlog_section(paths: BobrPaths, task_id: str | None = None) -> str:
    from bobr.core.cache import Cache

    cache = Cache(paths.cache_db)
    cache.sync(paths.backlog)

    lines = ["## Backlog", ""]

    if task_id:
        item = cache.get(task_id)
        if item:
            lines.append(f"### Current Task: {item.id}")
            lines.append("")
            lines.append(f"- **Title**: {item.title}")
            lines.append(f"- **Type**: {item.type.value}")
            lines.append(f"- **Priority**: {item.priority}")
            if item.area:
                lines.append(f"- **Area**: {', '.join(item.area)}")
            deps = cache.get_dependencies(item.id)
            if deps["depends_on"]:
                lines.append(f"- **Depends on**: {', '.join(deps['depends_on'])}")
            if deps["blocks"]:
                lines.append(f"- **Blocks**: {', '.join(deps['blocks'])}")
            lines.append("")

    # Summary
    all_items = cache.query()
    ready = cache.get_ready_items()
    in_progress = [i for i in all_items if i.status.value == "in-progress"]

    lines.append(f"**Total items**: {len(all_items)}  ")
    lines.append(f"**Ready**: {len(ready)}  ")
    lines.append(f"**In progress**: {len(in_progress)}")
    lines.append("")

    if in_progress:
        lines.append("### In Progress")
        lines.append("")
        for item in in_progress:
            assignee = f" ({item.assignee})" if item.assignee else ""
            lines.append(f"- {item.id} P{item.priority} {item.title}{assignee}")
        lines.append("")

    if ready:
        lines.append("### Ready for Work")
        lines.append("")
        for item in ready:
            lines.append(f"- {item.id} P{item.priority} {item.title}")
        lines.append("")

    cache.close()
    return "\n".join(lines)


def _conventions_section(paths: BobrPaths) -> str:
    """Include project conventions from config or knowledge."""
    lines = []

    # Check for knowledge/conventions.md or similar
    knowledge_dir = paths.bobr / "knowledge"
    conventions_files = [
        knowledge_dir / "conventions.md",
        knowledge_dir / "coding-standards.md",
    ]
    for f in conventions_files:
        if f.exists():
            text = f.read_text()
            if not lines:
                lines.append("## Conventions")
                lines.append("")
            lines.append(text.strip())
            lines.append("")

    return "\n".join(lines)


def _first_heading(text: str) -> str:
    """Extract the first markdown heading from text."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return ""


def _truncate(text: str, max_lines: int = 30) -> str:
    """Truncate text to max_lines, adding ellipsis if needed."""
    lines = text.splitlines()
    if len(lines) <= max_lines:
        return text
    return "\n".join(lines[:max_lines]) + "\n\n_(truncated)_"
